### ISSUE TITLE
Problems with the readme file

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/scipion-em-deepfinder#15]
Hello!
There are a couple of issues in the readme file here:
1- Why does it point to `~/.config/scipion/scipion.conf`? This config file doesn't exist anymore. If there is something in the config, then it should be done in `/path/to/scipion/config/scipion.conf`. So the thing with showing hidden files should be removed
2- The CONDA_ACTIVATION_CMD should not be changed! it is configured properly when scipion is installed like CONDA_ACTIVATION_CMD = eval "$(/path/to/conda/bin/conda shell.bash hook)" and should be left alone.

Cheers
Mohamad

**Comment by JorMaister** [comment]
We have updated it in https://github.com/scipion-em/scipion-em-deepfinder/pull/23
