### ISSUE TITLE
Class label is a problem if using other packages to pick

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/scipion-em-deepfinder#16]
Hello
Let's say that one uses template matching or manual picking with other packages, then going to deepfinder fails at the step of `generate sphere target` because the picks will not have a class label. In general, people will have only one class, their protein of interest, right? 
I found a workaround for this problem by `try` `except` in the protocol base (https://github.com/scipion-em/scipion-em-deepfinder/blob/devel/deepfinder/protocols/protocol_base.py in place of lines 64 and 88).
```
try:
    lbl = int(str(coord._dfLabel))
except:
    lbl = 1
```
I can make a PR if you wish.

Cheers
Mohamad

**Comment by JorMaister** [comment]
Hi, @MohamadHarastani!
First of all, thanks for reporting! I've been working the last weeks with DeepFinder and including some fixes and improvements, including this one, into a branch called jj_gen_target_parallelized. It will be merged soon 😃.

**Comment by JorMaister** [comment]
Solved in devel branch
