### ISSUE TITLE
Error using loaded model

### ISSUE THREAD

**Issue by Vilax** [scipion-em/scipion-em-deepfinder#20]
If the model is imported with the protocol load training model, then the segment protocol fails with the next error:

00022:   2023-07-31 12:44:45.251436: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5319 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1
00023:   Traceback (most recent call last):
00024:     File "/home/myhome/opt/scipion/software/em/deepfinder-0.2/bin/segment", line 50, in <module>
00025:       seg = Segment(Ncl=args.nclass, path_weights=args.path_weights, patch_size=args.psize)
00026:     File "/home/myhome/opt/scipion/software/em/deepfinder-0.2/deepfinder/inference.py", line 33, in __init__
00027:       self.net.load_weights(path_weights)
00028:     File "/home/myhome/opt/miniconda/envs/deepfinder-0.2/lib/python3.6/site-packages/keras/engine/training.py", line 2361, in load_weights
00029:       hdf5_format.load_weights_from_hdf5_group(f, self.layers)
00030:     File "/home/myhome/opt/miniconda/envs/deepfinder-0.2/lib/python3.6/site-packages/keras/saving/hdf5_format.py", line 703, in load_weights_from_hdf5_group
00031:       layer, weight_values, original_keras_version, original_backend)
00032:     File "/home/myhome/opt/miniconda/envs/deepfinder-0.2/lib/python3.6/site-packages/keras/saving/hdf5_format.py", line 404, in preprocess_weights_for_loading
00033:       weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
00034:     File "<__array_function__ internals>", line 6, in transpose
00035:     File "/home/myhome/opt/miniconda/envs/deepfinder-0.2/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 653, in transpose
00036:       return _wrapfunc(a, 'transpose', axes)
00037:     File "/home/myhome/opt/miniconda/envs/deepfinder-0.2/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
00038:       return bound(*args, **kwds)
00039:   ValueError: axes don't match array
00040:   Traceback (most recent call last):
00041:     File "/home/myhome/opt/scipion/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 204, in run
00042:       self._run()
00043:     File "/home/myhome/opt/scipion/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 255, in _run
00044:       resultFiles = self._runFunc()
00045:     File "/home/myhome/opt/scipion/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 251, in _runFunc
00046:       return self._func(*self._args)
00047:     File "/home/myhome/opt/scipion/plugins/scipion-em-deepfinder/deepfinder/protocols/protocol_segment.py", line 86, in launchSegmentationStep
00048:       Plugin.runDeepFinder(self, 'segment', deepfinder_args, gpuId=getattr(self, GPU_LIST).get())
00049:     File "/home/myhome/opt/scipion/plugins/scipion-em-deepfinder/deepfinder/__init__.py", line 66, in runDeepFinder
00050:       protocol.runJob(fullProgram, args, env=cls.getEnviron(gpuId=gpuId), cwd=cwd)
00051:     File "/home/myhome/opt/scipion/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 1507, in runJob
00052:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00053:     File "/home/myhome/opt/scipion/scipion-pyworkflow/pyworkflow/protocol/executor.py", line 65, in runJob
00054:       process.runJob(log, programName, params,
00055:     File "/home/myhome/opt/scipion/scipion-pyworkflow/pyworkflow/utils/process.py", line 56, in runJob
00056:       return runCommand(command, env, cwd)
00057:     File "/home/myhome/opt/scipion/scipion-pyworkflow/pyworkflow/utils/process.py", line 71, in runCommand
00058:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
00059:     File "/home/myhome/opt/miniconda/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
00060:       raise CalledProcessError(retcode, cmd)
00061:   subprocess.CalledProcessError: Command ' eval "$(/home/myhome/opt/miniconda/condabin/conda shell.bash hook)"&& conda activate deepfinder-0.2 && /home/myhome/opt/scipion/software/em/deepfinder-0.2/bin/segment -t Runs/000292_ProtImodTomoReconstruction/extra/TS_011/IS002_291013_011.mrc -w /home/myhome/ScipionUserData/projects/10045/Runs/000579_DeepFinderTrain/extra/net_weights_FINAL.h5 -c 1 -p 100 -o /home/myhome/ScipionUserData/projects/10045/Runs/000789_DeepFinderSegment/extra/segmentation_IS002_291013_011.mrc' returned non-zero exit status 1.
00062:   Protocol failed: Command ' eval "$(/home/myhome/opt/miniconda/condabin/conda shell.bash hook)"&& conda activate deepfinder-0.2 && /home/myhome/opt/scipion/software/em/deepfinder-0.2/bin/segment -t Runs/000292_ProtImodTomoReconstruction/extra/TS_011/IS002_291013_011.mrc -w /home/myhome/ScipionUserData/projects/10045/Runs/000579_DeepFinderTrain/extra/net_weights_FINAL.h5 -c 1 -p 100 -o /home/myhome/ScipionUserData/projects/10045/Runs/000789_DeepFinderSegment/extra/segmentation_IS002_291013_011.mrc' returned non-zero exit status 1.

**Comment by JorMaister** [comment]
Solved
