### ISSUE TITLE
DeepFinder requirest to anotate all tomograms in the list

### ISSUE THREAD

**Issue by Vilax** [scipion-em/scipion-em-deepfinder#22]
If a tomogram has no particles the user will not annotate that tomogram. However, for deepfinder is mandatory to annotate it. Otherwise the output is not generated. A generate output button should be created.

![image](https://github.com/scipion-em/scipion-em-deepfinder/assets/12271438/f70b06e9-9c59-4896-b91c-16f7c1893e66)

**Comment by JorMaister** [comment]
Solved, BUT:

Annotation protocol now allows to generate the output even though not all the tomograms have been annotated.
IMPORTANT: until some requested changes in the source code are carried out, the tomograms can only be annotated
once. Otherwise, its coordinates are lost.
