### ISSUE TITLE
Try to make the clustering protocol faster (with lower binning)

### ISSUE THREAD

**Issue by JorMaister** [scipion-em/scipion-em-deepfinder#26]
Reported by @MohamadHarastani. Thanks!

**Comment by MohamadHarastani** [comment]
My pleasure! I just noticed that this is already implemented with deepfinder
https://github.com/deep-finder/deep-finder/blob/main/deepfinder/bin/segment.py#L29

**Comment by MohamadHarastani** [comment]
Hi again
I found that tomosegmemtv has a protocol for resizing tomomasks and is compatible with DeepFinder's clustering step. I think this issue is obsolete.
Cheers
